### PR TITLE
German.md

### PR DESCRIPTION
**Pull request by Daksheshapkare**

### CODE REVIEW

**Comment by Daksheshapkare** [comment]
> @Daksheshapkare You're just spamming PR #92, #91, #90, and #87 I can't merge any of them as I'm finding empty files (containing no content). I tried to guide you as much as I could, but I'm sorry you're doing it in the wrong way.
> This is not the way to Contribute to any Open Source repo.

So what kind of code should i put

**Comment by Daksheshapkare** [comment]
I am trying ny watching YouTube video
I will post translation of readme pr 
Is it okay

**Comment by Ashish-khanagwal** [comment]
> I am trying ny watching YouTube video I will post translation of readme pr Is it okay

Please, first create issue on that then make PR

**Comment by Daksheshapkare** [comment]
> > I am trying ny watching YouTube video I will post translation of readme pr Is it okay
> 
> Please, first create issue on that then make PR

On which pr

**Comment by Daksheshapkare** [comment]
On which code

**Comment by Ashish-khanagwal** [comment]
On the original repo, go to the issues section and create an issue about changes you want to make or resources you want to add

**Comment by Ashish-khanagwal** [comment]
> > > > I am trying ny watching YouTube video I will post translation of readme pr Is it okay
> > > 
> > > 
> > > Please, first create issue on that then make PR
> > 
> > 
> > On which pr
> 
> As you have closed the pr I will make a readme file on French German ,etc separately. If any issue i will contact you I will try to make cleanly Please give me your no. To msg to give you the report

Reach out to me on the Discord server.

**Pull request closed without merging**
