### PR TITLE
Readme in french language

### PR DESCRIPTION
**Pull request by Daksheshapkare**

### CODE REVIEW

**Review by Ashish-khanagwal — CHANGES_REQUESTED** [review]
Hey @Daksheshapkare, Please create another folder and create a file for Readme in french named after `French.md` and then translate it.
And make sure to translate the original Readme without any modification. Use the proper Banner and links, you can find them in the original Readme, If you face any difficulty then reach out to me. Don't include index and resources.
For more clarification, you can have a look at the Spanish readme file.

**Comment by Daksheshapkare** [comment]
Please send me the links of the banner so I can copy paste it 
As I don't know what to do to paste the banner In my README as I am a new user in. Github

**Comment by Daksheshapkare** [comment]
> Hey @Daksheshapkare, Please create another folder and create a file for Readme in french named after `French.md` and then translate it.
> And make sure to translate the original Readme without any modification. Use the proper Banner and links, you can find them in the original Readme, If you face any difficulty then reach out to me. Don't include index and resources.
> For more clarification, you can have a look at the Spanish readme file.

Please send me the links of the banner so I can copy paste it 
As I don't know what to do to paste the banner In my README as I am a new user in. Github

**Comment by Ashish-khanagwal** [comment]
> > Hey @Daksheshapkare, Please create another folder and create a file for Readme in french named after `French.md` and then translate it.
> > And make sure to translate the original Readme without any modification. Use the proper Banner and links, you can find them in the original Readme, If you face any difficulty then reach out to me. Don't include index and resources.
> > For more clarification, you can have a look at the Spanish readme file.
> 
> Please send me the links of the banner so I can copy paste it As I don't know what to do to paste the banner In my README as I am a new user in. Github

Banner :point_down: 
```
<p align="center"><img src="https://user-images.githubusercontent.com/75534912/194343020-6cbd2485-c2ea-4779-87e2-9708238398e7.png"></p>
```
Socials :point_down: 
```
<div align="center">
<a href="https://twitter.com/codeforcomm"> <img src="https://img.shields.io/badge/Twitter-%231DA1F2CFC.svg?style=for-the-badge&logo=Twitter&logoColor=white"/><a>
<a href="https://discord.gg/AfYcurdCd3"><img src="https://img.shields.io/badge/%3CCode For Community%3E-%237289DA.svg?style=for-the-badge&logo=discord&logoColor=white"/></a>
<a href="https://twitter.com/iashishkhangwal"> <img src="https://img.shields.io/badge/Twitter-%231DA1F2.svg?style=for-the-badge&logo=Twitter&logoColor=white"/><a>
<a href="https://www.linkedin.com/in/ashish-khanagwal-890326213/"><img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white"/></a>
</div>
```

**Comment by Daksheshapkare** [comment]
> > > Hey @Daksheshapkare, Please create another folder and create a file for Readme in french named after `French.md` and then translate it.
> > > And make sure to translate the original Readme without any modification. Use the proper Banner and links, you can find them in the original Readme, If you face any difficulty then reach out to me. Don't include index and resources.
> > > For more clarification, you can have a look at the Spanish readme file.
> > 
> > Please send me the links of the banner so I can copy paste it As I don't know what to do to paste the banner In my README as I am a new user in. Github
> 
> Banner :point_down: 
> ```
> <p align="center"></p>
> ```
> Socials :point_down: 
> ```
> <div align="center">
> <a href="https://twitter.com/codeforcomm"> <a>
> <a href="https://discord.gg/AfYcurdCd3"></a>
> <a href="https://twitter.com/iashishkhangwal"> <a>
> <a href="https://www.linkedin.com/in/ashish-khanagwal-890326213/"></a>
> </div>
> ```


So if I paste this in my readme then I will get the img of banner right?

**Comment by Ashish-khanagwal** [comment]
yes, If not then ping me

**Review by Ashish-khanagwal — CHANGES_REQUESTED** [review]
Please, don't modify it with extra spaces. As I gave to you just copy and paste that content

**Comment by Daksheshapkare** [comment]
> Please, don't modify it with extra spaces. As I gave to you just copy and paste that content

Done

**Comment by Ashish-khanagwal** [comment]
Delete all other files `French.md`, `Readme in french`, and `readme in french`

**Comment by Ashish-khanagwal** [comment]
delete other files too, as I mentioned above. look carefully

**Comment by Daksheshapkare** [comment]
> Delete all other files `French.md`, `Readme in french`, and `readme in french`
> and please sync it, I already mentioned how to sync...It'll be creating merge conflicts

I have synced please check it

**Comment by Daksheshapkare** [comment]
Please yourself delete the file . As my computer hanged
I have allow to edit maintainer

**Pull request closed without merging**
