### PR TITLE
Created Design Tab and added Resources

### PR DESCRIPTION
**Pull request by DevGupta-ikr**
Hey, I have added the resources, hope it helps.

### CODE REVIEW

**Review by Ashish-khanagwal — APPROVED** [review]
Awesome work :fire:
Code looks good to me

**Comment by DevGupta-ikr** [comment]
Hey, could you please add the hacktoberfest accepted label to my pr ?

**Comment by Ashish-khanagwal** [comment]
It's good, you want to contribute to hacktoberfest, but to contribute to Hacktoberfest you have to contribute to repos that contain `hackotberfest` label.

hacktoberfest

**Comment by DevGupta-ikr** [comment]
Cool, thanks.

**Comment by Ashish-khanagwal** [comment]
hey @DevGupta-ikr , This repo is also labeled under Hactoberfest 2022. So, you can contribute now and have some green squares / get merge requests needed for hacktoberfest

**Pull request merged**
