### PR TITLE
Added DSA resources links

### PR DESCRIPTION
**Pull request by geetika001**
Have added some useful resources links for DSA.Please review and let me know for further changes,I'll do the same.
Also Please consider for Hacktoberfest.

### CODE REVIEW

**Review by Ashish-khanagwal — CHANGES_REQUESTED** [review]
@geetika001 Please add resources in README.md, don't create any other file (DSAresources.md).
One more thing doesn't upload photos, only working links are allowed.

**Comment by geetika001** [comment]
@Ashish-khanagwal photos are nothing but links.if u click them,u will be redirected.But please confirm if u still want me to remove them.As of now adding DSAresources.md content to README.md

**Comment by Ashish-khanagwal** [comment]
@geetika001 you can create a new file as DSAresources.md but make sure to link it with README.md.
Use links instead of photos (Highly recommended)

**Comment by Ashish-khanagwal** [comment]
this is, what adding images looks like 👇 

dsa

**Comment by geetika001** [comment]
Yeah sorry.Actually had added the wrong address for pepcoding.Correcting that

**Comment by geetika001** [comment]
But please check in case clicking on other images is working?Otherwise I'm only adding links and removing the images

**Comment by Ashish-khanagwal** [comment]
> But please check in case clicking on other images is working?Otherwise I'm only adding links and removing the images

I'm highly +ve on it, Add links instead of photos

**Review by Ashish-khanagwal — APPROVED** [review]
Thank you for contributing :fire:

**Comment by geetika001** [comment]
@Ashish-khanagwal thanks for merging the PR.
Even I was about to pull request after adding more resources and changes.Though,thanks again.

**Comment by Ashish-khanagwal** [comment]
you're welcome, Thank you for your collaboration 👍

**Pull request merged**
